/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "rcc.h"
#include "gpio.h"
#include "mm_addresses.h"

void someDelay()
{
	for(int i=0; i<500000; i++);
}

int main(void)
{
	// 1. provide clock for both GPIOA and GPIOD Peripherals
	pRCC_AHB1ENR->gpioa_en = 1; // 1: enable, 0:disable
	pRCC_AHB1ENR->gpiod_en = 1;

	// 2. Configure GPIOA.0 as input pin and GPIOD.12,13,14 & 15 as output pins
	// Note: 0: input, 1: GP Output, 2: AF, 3: Analog
	pGPIOA_MODER->moder0 = 0;
	pGPIOD_MODER->moder12 = 1;
	pGPIOD_MODER->moder13 = 1;
	pGPIOD_MODER->moder14 = 1;
	pGPIOD_MODER->moder15 = 1;

    /* Loop forever */
	for(;;)
	{
		if(pGPIOA_IDR->idr0 == 1){
			someDelay();
			pGPIOD_ODR->odr12 = ~pGPIOD_ODR->odr12;
			pGPIOD_ODR->odr13 = ~pGPIOD_ODR->odr13;
			pGPIOD_ODR->odr14 = ~pGPIOD_ODR->odr14;
			pGPIOD_ODR->odr15 = ~pGPIOD_ODR->odr15;
		}

	}
}
